services:
  - type: web
    name: safemed
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MOCK_API
        value: true
      - key: BASE_URL
        value: https://hackathon-api.aheadafrica.org
      - key: API_TOKEN
        sync: false
